### ISSUE TITLE
Publish the latest code as a new version of the crypto plugin

### ISSUE THREAD

**Issue by superflav** [ricardojmendez/grails-encryption#2]
A patch was accepted from me a year ago, but the updates still have not been published to the Grails plugin repository. It'd be great if it were rolled out so the greater Grails community could start making use of it.

$ grails -plain-output plugin-info crypto

    --------------------------------------------------------------------------
    Information about Grails plugin
    --------------------------------------------------------------------------
    Name: crypto    | Latest release: 2.0
    --------------------------------------------------------------------------
    Encryption plugin for Grails
    --------------------------------------------------------------------------
    Author: Ricardo J. Mendez and Robert Fischer
    --------------------------------------------------------------------------
    Author's e-mail: ricardo@arquetipos.co.cr
    --------------------------------------------------------------------------

    Masks encryption and decryption functions, currently integrated with Bouncy
    Castle. This version provides classes for PGP and Blowfish, as well as a
    tool for both generating random passwords and salting / verifying salted
    passwords.

    Dependency Definition
    --------------------------------------------------------------------------
        :crypto:2.0

**Comment by joshua-moore** [comment]
I'd be happy to take over and manage publishing this plugin.

**Comment by ricardojmendez** [comment]
The offer is much appreciated @joshua-moore, I've added you as a collaborator.

**Comment by irusev** [comment]
It looks like the plugin is published and Approved, but for some reason still stays in 'Pending' status for the last 2 years.

https://grails.org/plugins/pending/631

Anyone has an idea why is that?

**Comment by ricardojmendez** [comment]
Sorry @irusev, I don't know. Looks like @joshua-moore submitted it like he said he was going to, and then it just stayed there.

You may want to ask on the plugin page itself.
